### ISSUE TITLE
Screencast Portal

### ISSUE THREAD

**Issue by colinkiama** [elementary/portals#74] opened 2023-05-13 12:40 UTC
### Problem

Currently unable to use some screen recording Flatpak apps because they can't use the [`org.freedesktop.portal.ScreenCast`](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.ScreenCast) portal in elementary OS. e.g: [Kooha](https://flathub.org/en-GB/apps/io.github.seadve.Kooha)

### Proposal

Implement [org.freedesktop.impl.portal.ScreenCast`](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.impl.portal.ScreenCast). It would improve support for Flatpak apps that use screen recording to work on elementary OS.

It would allow apps to use implement screen recording features without needing to know about the desktop or window manager that the app is running on.

### Prior Art (Optional)

[xdg-desktop-portal-gnome](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/) (see: src/screencast.c)
[xdg-desktop-portal-kde](https://invent.kde.org/plasma/xdg-desktop-portal-kde) (see: src/screencast.cpp)

P.S. I also see that both desktop portal implementations also have screencast dialog. Not sure how relevant that may be for this but it seems like something worth taking a look at too.

**Comment by leolost2605** [comment] 2024-04-04 13:42
Marked as blocking for wayland because IMHO having no working screen recording at all on wayland is too big of a regression

**Comment by danirabbit** [comment] 2024-07-03 15:50
Fixed in #102

**Closed by danirabbit** 2024-07-03 15:50 UTC
