### ISSUE TITLE
Portal can't be registered

### ISSUE THREAD

**Issue by danirabbit** [elementary/portals#22] opened 2021-10-19 23:31 UTC
### What Happened?

Not sure exactly when this started happening, but I did a clean install because I thought it was my fault.

### Steps to Reproduce

Have an app try to launch the open_uri portal like Epiphany opening a download

### Expected Behavior

Portal should launch ;) 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
While running Epiphany:

** (epiphany:2): WARNING **: 16:24:04.119: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.OpenURI” on object at path /org/freedesktop/portal/desktop

From journalctl:

Oct 19 12:25:53 Danis-Mini xdg-desktop-por[1625]: Failed to create app chooser proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.pantheon: Timeout was reached
```

**Comment by Marukesu** [comment] 2021-10-20 00:17
seems to be the same as elementary/pantheon-agent-polkit#30, since meson install it in `/usr/libexec` as expected.

in the `deb-packaging` branch, i think it's need a `io.elementary.portals.install` file like the one in [files](https://github.com/elementary/files/blob/deb-packaging/debian/pantheon-files.install).

**Comment by Marukesu** [comment] 2021-10-20 03:16
Ok, the issue is a circular dependency [here](https://github.com/elementary/portals/blob/main/src/XdgDesktopPortalPantheon.vala#L55-L62):

`xdg-desktop-portal` try to open `xdg-desktop-portal-pantheon` that calls `Granite.Settings.prefers_color_scheme` that  try to call the settings portal frontend on xdg-desktop-portal.

Moving it to the dialog classes seems to fix it.

**Closed as completed** 2021-10-20 19:03 UTC
